### ISSUE TITLE
 pushea al registry de github

### ISSUE THREAD

**Issue by paganuzzi** [paganuzzi/stacklaravel#3]
push images to github registry

**Comment by paganuzzi** [comment]
```
 -
        name: Build and push php
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: <DockerFileName>
          tags: ghcr.io/paganuzzi/<image-name>:${{ steps.tag.outputs.tag }}
```
